### ISSUE TITLE
jar deploy problem

### ISSUE THREAD

**Issue by yota4649** [marklogic-community/data-explorer#115]
we have the following error when java -jar data-explorer.jar deploy, probably some configuration at server side, but please let us know how we can find root cause for this error. thank you

$ sudo java -jar data-explorer.jar deploy
16:23:11.199 INFO  Deploying Data-Explorer...
16:23:12.979 INFO  Wrote application configuration files to path: /tmp/com.marklogic.dataexplorer-1524640992910
16:23:13.314 INFO  Deploying application...
Exception in thread "main" org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8002/manage/v2/privileges": Connection reset; nested exception is java.net.SocketException: Connection reset
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:628)
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:303)
        at com.marklogic.mgmt.ManageClient.getXmlStringAsAdmin(ManageClient.java:150)
        at com.marklogic.mgmt.ManageClient.getXmlAsAdmin(ManageClient.java:154)
        at com.marklogic.mgmt.resource.AbstractResourceManager.getAsXml(AbstractResourceManager.java:49)
        at com.marklogic.mgmt.resource.AbstractResourceManager.exists(AbstractResourceManager.java:45)
        at com.marklogic.mgmt.resource.AbstractResourceManager.save(AbstractResourceManager.java:84)
        at com.marklogic.appdeployer.command.AbstractCommand.saveResource(AbstractCommand.java:137)
        at com.marklogic.appdeployer.command.AbstractResourceCommand.processExecuteOnResourceDir(AbstractResourceCommand.java:45)
        at com.marklogic.appdeployer.command.AbstractResourceCommand.execute(AbstractResourceCommand.java:31)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.executeCommand(AbstractAppDeployer.java:107)
        at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:66)
        at com.marklogic.dataexplorer.ClasspathDeployer.processRequest(ClasspathDeployer.java:60)
        at com.marklogic.dataexplorer.command.DeployCommand.doExecute(DeployCommand.java:17)
        at com.marklogic.dataexplorer.command.AbstractCommand.execute(AbstractCommand.java:21)
        at com.marklogic.dataexplorer.Main.main(Main.java:42)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
       at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:89)
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:652)
        ... 16 more

**Comment by markschiffner** [comment]
Can you execute the command directly and get the list of privileges? 
http://localhost:8002/manage/v2/privileges

**Comment by markschiffner** [comment]
@yota4649 Has your issue been resolved?  If so, can we add any resolution to ticket for future reference.

**Comment by yota4649** [comment]
Sorry for not rersponding

I asked instead of out customer and I am asking this result now.

I can’t reproduce it in my environment. I think it may be network or other environment.

But I only know the error happens at this time. 

Please keep waiting for a while.

 

Thank you 

YO

**Comment by yota4649** [comment]
Hi

 

No, jar deploy doesn’t work yet.

**Comment by markschiffner** [comment]
Ok, just making sure.  
1. Was the jar load test done from the same system as the http://localhost:8002/manage/v2/privileges test?
2. Is the server on AWS or behind a loadbalancer?  Sometimes there are timeouts set or routing issues.
3. Where any of the server timeout settings changed?  I am guessing no.

**Comment by markschiffner** [comment]
Another recommendation (from @rjrudin ) is to make a new ml-gradle project and see if you can do an mlDeploy with that.  If you haven't done it before, you can make a simple project https://github.com/marklogic-community/ml-gradle/wiki/Getting-started.  That would give an independent test of connectivity using the same infrastructure that data explorer uses.

**Comment by yota4649** [comment]
this was resolved. It was happened because user had set ssl on port 8002.
