### ISSUE TITLE
Getting 404 No found error while accessing data-explorer port

### ISSUE THREAD

**Issue by sumanthbolisetti** [marklogic-community/data-explorer#191]
I have installed the data explorer package as per the instructions. Installation succeded and i see the newly created appservers, databases, users and roles. When i am trying to access the port i am getting $04 Not Found error. I suspect it is an issue with app servers setting 'Url Rewriter' or 'Error handler'. Do i need to place the files some where in our databases server to be able to access by application server? Please advice. We are new to MarkLogic.

**Comment by markschiffner** [comment]
Install should put files in correct location. You are accessing via port 7777?
Are you changing any of the app server setting for the data explorer?
Can you please provide any additional information and the messages in error log. 

Regards

**Comment by sumanthbolisetti** [comment]
hi Mark,
  We didnt changed any settings in app servers and the deployment package is deployed as is.  We raised a ticket with MarkLogic Support and which help of them we did a test to check if the databases are accessible, we created a new app server and attached data-explorer databases to those app server and loaded a document to data-explorer-modules database and i am able to access when accessing using new app server. But from old app server we are getting 404 error. ML Support suspects its an issue with error.xqy and rewriter.xqy files and app server is not able to find those files which is causing the error. 

app server Log:
10.69.69.124 - admin [04/Jun/2019:13:56:00 -0400] "GET /test.html HTTP/1.1" 404 203 - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"
10.69.69.124 - admin [04/Jun/2019:13:59:38 -0400] "GET / HTTP/1.1" 404 203 - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

**Comment by markschiffner** [comment]
Ok, not sure I am following.  Lets start here:
You should have a database(s) and app server for your application.
You should also have Data-Explorer-content and Data-Explorer-modules databases and a Data-Explorer app server on port 7777.
When you go to hostname:7777 you should get the DataExplorer application and begin configuring.

**Comment by sumanthbolisetti** [comment]
yes, i have Data-explorer databases and app server on port 7777. And when i tried to go to hostname:7777, i am getting 404 Not Found error. Below is the app server config. 

`{"server-name":"Data-Explorer", "group-name":"Default", "server-type":"http", "enabled":true, "root":"/", "port":7777, "webDAV":false, "execute":true, "display-last-login":false, "address":"0.0.0.0", "backlog":512, "threads":32, "request-timeout":30, "keep-alive-timeout":5, "session-timeout":3600, "max-time-limit":3600, "default-time-limit":600, "max-inference-size":500, "default-inference-size":100, "static-expires":3600, "pre-commit-trigger-depth":1000, "pre-commit-trigger-limit":10000, "collation":"http://marklogic.com/collation/", "coordinate-system":"wgs84", "authentication":"basic", "internal-security":true, "concurrent-request-limit":0, "compute-content-length":false, "file-log-level":"info", "log-errors":true, "debug-allow":true, "profile-allow":true, "default-xquery-version":"1.0-ml", "multi-version-concurrency-control":"contemporaneous", "distribute-timestamps":"fast", "output-sgml-character-entities":"none", "output-encoding":"UTF-8", "output-method":"default", "output-byte-order-mark":"default", "output-cdata-section-namespace-uri":"", "output-cdata-section-localname":null, "output-doctype-public":"", "output-doctype-system":"", "output-escape-uri-attributes":"default", "output-include-content-type":"default", "output-indent":"default", "output-indent-untyped":"default", "output-indent-tabs":"default", "output-media-type":"", "output-normalization-form":"none", "output-omit-xml-declaration":"default", "output-standalone":"omit", "output-undeclare-prefixes":"default", "output-version":"", "output-include-default-attributes":"default", "default-error-format":"compatible", "error-handler":"/server/error.xqy", "url-rewriter":"/server/rewrite.xqy", "rewrite-resolves-globally":true, "ssl-allow-sslv3":true, "ssl-allow-tls":true, "ssl-disable-sslv3":false, "ssl-disable-tlsv1":false, "ssl-disable-tlsv1-1":false, "ssl-disable-tlsv1-2":false, "ssl-hostname":"", "ssl-ciphers":"ALL:!LOW:@STRENGTH", "ssl-require-client-certificate":true, "content-database":"Data-Explorer-content", "modules-database":"Data-Explorer-modules", "default-user":"admin"}`

**Comment by markschiffner** [comment]
OK, great. Can you check to make sure there are modules in the Data explorer modules database.

**Comment by sumanthbolisetti** [comment]
when i hit explore i dont see any modules in the data-explorer-modules. Modules database is empty.

**Comment by sumanthbolisetti** [comment]
hi Mark, I tied to redeploy data-explorer and i am getting following exception when deploying. Got similar message when i deployed first time as well. could this be the issues? how to resolve this issue, any insight. 

root@imml-db07d /data/ml_install $ java -DmlPassword='ML@dev!Tease' -DmlHost=imml-db07d -jar data-explorer-0.10.jar deploy
10:37:12.176 INFO  Deploying Data-Explorer...
10:37:12.540 INFO  Wrote application configuration files to path: /tmp/com.marklogic.dataexplorer-1559831832521
10:37:12.633 INFO  Deploying application...
Exception in thread "ThreadPoolTaskExecutor-1" java.lang.IllegalArgumentException: unsupported auth scheme: [Basic realm=public]
        at com.burgstaller.okhttp.digest.DigestAuthenticator.findDigestHeader(DigestAuthenticator.java:198)
        at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:163)
        at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:30)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:289)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:157)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
        at com.marklogic.client.impl.OkHttpServices.makeFirstRequest(OkHttpServices.java:500)
        at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4050)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3353)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:48)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
10:37:29.437 INFO  Deployed Data-Explorer

**Comment by markschiffner** [comment]
I believe the "unsupported auth scheme: [Basic realm=public]" message is
that the authorization incorrect.
Check the 8000 is set to basic or digest and try reverse and reinstall.I
will try to verify it later.

**Comment by markschiffner** [comment]
Has this resolved your issue?

**Comment by markschiffner** [comment]
I am guessing this has resolved the issues
